### ISSUE TITLE
JavaScript EcoSystem Decision

### ISSUE THREAD

**Issue by andi1984** [tapas-cantina/cantina#2]
There is an open question about which JavaScript eco system we should choose for Cantina.

Here are my thoughts about different candidates. Feel free to discuss or add your opinion.

**Comment by andi1984** [comment]
# AngularJS v2

Pros:

- WebComponent friendly
- Many built-in functionality

Cons:

- Syntax
- Is a framework and thus may restrict our tooling, the vendor JavaScript we might use
- Probably long learning curve

**Comment by andi1984** [comment]
# React

Pros

- At the end it is plain old vanilla JavaScript
- Probably faster learning curve
- Doesn't restrict us much in the tools or JS components we might want to use

Cons

- Not so many built-in functionality
- [Doesn't allow to wait for an asynchronous request to finally render the module](https://github.com/facebook/react/issues/1739)

**Comment by domma** [comment]
I don't have a strong opinion, agree with your pros/cons and I'm happy to follow your decision. As the admin interface will be rather form based stuff, Angular2 might be a good choice. As you know, I might be able to pull in some expert knowledge, if you ask me to do so. What about giving Angular2 a try, do a spike and see how it works. If it works fine, we go for it. If not, we switch to React.

**Comment by andi1984** [comment]
I agree, so let's start us with Angular 2!

**Comment by jedwards1211** [comment]
@andi1984 FYI, there's nothing about React that isn't WebComponent-friendly.  See:
https://facebook.github.io/react/docs/webcomponents.html
https://github.com/PixelsCommander/ReactiveElements

**Comment by andi1984** [comment]
@jedwards1211 Thx Andy for pointing this out. I updated my pro/con list above. As you might have already seen in the develop branch we currently stick with Angular2, but as @domma said: if we detect problems using it in the near future we will switch to React.
